// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://putgjtmfpjlpvxpntxzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1dGdqdG1mcGpscHZ4cG50eHp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzA3MTgsImV4cCI6MjA3Mzc0NjcxOH0.4wGcGrPM6v0xQuwVnbwad9h1LJjGWY0J2FGZA4pNd00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});