// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uadecgtduzejunquvbir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZGVjZ3RkdXplanVucXV2YmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDUxMTksImV4cCI6MjA2MTgyMTExOX0.uphVbQ_ALJpwor4CYhBuCYbvldtD6ZhHjoVdBbxbahg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);